name: Feature request
description: Suggest a new feature or enhancement. ✨
title: "[Feature] "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the details below to help us understand your request.

  - type: textarea
    id: description
    attributes:
      label: Detailed description
      description: A detailed description of the feature request
      placeholder: "Describe the feature in detail, including the problem it solves, the benefits it provides, and any additional context."
    validations:
      required: true

  - type: input
    id: examples
    attributes:
      label: Examples
      description: Any examples or mockups to help illustrate the feature
      placeholder: "e.g., Provide a screenshot or a link to a similar feature"
    validations:
      required: false

  - type: input
    id: additional_context
    attributes:
      label: Additional context
      description: Any other context or information you want to provide
      placeholder: "e.g., Why is this feature important to you?"
    validations:
      required: false
